---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 3Gi } }
---
apiVersion: v1
kind: Pod
metadata:
  name: pgstrom-test
spec:
  restartPolicy: OnFailure
  containers:
    - name: pgstrom-container
      image: "localhost:32000/mypg14-rocky8:test1"
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: pvc
          mountPath: /var/lib/pgsql/14/data
      tty: true
      resources:
        limits:
          cpu: 200m
          memory: 4096Mi
          nvidia.com/gpu: 1
  volumes:
    - name: dshm
      emptyDir:
         medium: Memory
    - name: pvc
      persistentVolumeClaim:
        claimName: test-pvc
